/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionUsuarios.h"


void
gestion_usuario_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	proxNodo  registrarusuario_1_arg;
	proxNodo  *result_2;
	char *listarusuarios_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_usuario, gestion_usuario_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = registrarusuario_1(&registrarusuario_1_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = listarusuarios_1((void*)&listarusuarios_1_arg, clnt);
	if (result_2 == (proxNodo *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_usuario_1 (host);
exit (0);
}
