/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gestionUsuarios.h"

bool_t
xdr_proxNodo (XDR *xdrs, proxNodo *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct nodo_usuario), (xdrproc_t) xdr_nodo_usuario))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_usuario (XDR *xdrs, nodo_usuario *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nombres, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->apellidos, MAXAPEL,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->codigo, MAXAPEL,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_proxNodo (xdrs, &objp->nodoSiguiente))
		 return FALSE;
	return TRUE;
}
