/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GESTIONUSUARIOS_H_RPCGEN
#define _GESTIONUSUARIOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 30
#define MAXAPEL 30

typedef struct nodo_usuario *proxNodo;

struct nodo_usuario {
	char nombres[MAXNOM];
	char apellidos[MAXAPEL];
	char codigo[MAXAPEL];
	proxNodo nodoSiguiente;
};
typedef struct nodo_usuario nodo_usuario;

#define gestion_usuario 0x20000001
#define gestion_usuario_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define registrarUsuario 1
extern  bool_t * registrarusuario_1(proxNodo *, CLIENT *);
extern  bool_t * registrarusuario_1_svc(proxNodo *, struct svc_req *);
#define listarUsuarios 2
extern  proxNodo * listarusuarios_1(void *, CLIENT *);
extern  proxNodo * listarusuarios_1_svc(void *, struct svc_req *);
extern int gestion_usuario_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registrarUsuario 1
extern  bool_t * registrarusuario_1();
extern  bool_t * registrarusuario_1_svc();
#define listarUsuarios 2
extern  proxNodo * listarusuarios_1();
extern  proxNodo * listarusuarios_1_svc();
extern int gestion_usuario_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_proxNodo (XDR *, proxNodo*);
extern  bool_t xdr_nodo_usuario (XDR *, nodo_usuario*);

#else /* K&R C */
extern bool_t xdr_proxNodo ();
extern bool_t xdr_nodo_usuario ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GESTIONUSUARIOS_H_RPCGEN */
